version: "3.9"

services:

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adal
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  flask-web:
    build: .
    ports:
      - "8000:5000"
    links:
      - mongo-db

volumes:
  mongo-data: